// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJctv_nML0-lcP8017GsVzjKneBsgiEuU',
    appId: '1:633351554586:android:773985c9f07162987633a3',
    messagingSenderId: '633351554586',
    projectId: 'fitween-v1',
    databaseURL: 'https://fitween-v1-default-rtdb.firebaseio.com',
    storageBucket: 'fitween-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDLIu0b86RW1khrCGSu8j15EJ_4Fo4nQQ',
    appId: '1:633351554586:ios:89cb60631faf92bc7633a3',
    messagingSenderId: '633351554586',
    projectId: 'fitween-v1',
    databaseURL: 'https://fitween-v1-default-rtdb.firebaseio.com',
    storageBucket: 'fitween-v1.appspot.com',
    iosClientId: '633351554586-jjkah84abeij1q8ki1ubvm55diam0et4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitween1',
  );
}
